#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use DFrame\Command\Console;
use App\Console\VersionCommand;

use DFrame\Reports\Report;
Report::setup(true,  __DIR__ . '/public/logs/html.log', Report::cli());

// Khởi tạo console
$console = new Console();

// Đăng ký command
$console->register(new VersionCommand());

// Chạy command từ CLI
$console->run($argv);
