#!/usr/bin/env php
<?php

define('ROOT_DIR', __DIR__ . '/');
define('INDEX_DIR', __DIR__ . '/public/');

require_once __DIR__ . '/vendor/autoload.php';

use DFrame\Application\App;
use DFrame\Reports\Report;

Report::setup(true, INDEX_DIR . 'logs/cli.log', Report::cli());

App::initialize()->bootDli($argv);
